import type { ModelAdapter, ModelRequest, ModelResponse } from './adapter';

// ---------------------------------------------------------------------------
// Static mock payloads — valid against the Zod schemas in @aifactory/contracts
// ---------------------------------------------------------------------------

function mockPlannerResponse(): object {
  return {
    requirementId: 'MOCK',
    summary: 'Mock plan — no real LLM was called (dry-run mode).',
    tasks: [
      {
        id: 'task-mock-1',
        title: 'Implement mock feature',
        description: 'A placeholder task generated by the mock model adapter.',
        dependsOn: [],
        acceptanceCriteria: [
          'Feature should be reachable via its public API',
          'Unit tests must pass',
        ],
        targetFiles: ['src/mock/feature.ts'],
      },
    ],
    assumptions: ['This is a dry-run — no actual model was invoked.'],
    outOfScope: [],
  };
}

function mockArchitectResponse(taskId: string): object {
  return {
    taskId,
    components: [
      {
        name: 'MockFeature',
        type: 'file',
        path: 'src/mock/feature.ts',
        description: 'Main feature implementation.',
        dependencies: [],
      },
      {
        name: 'MockFeatureTest',
        type: 'test',
        path: 'src/mock/feature.test.ts',
        description: 'Unit tests for MockFeature.',
        dependencies: ['src/mock/feature.ts'],
      },
    ],
    patterns: ['module'],
    risks: [],
  };
}

function mockCoderResponse(taskId: string): object {
  return {
    taskId,
    patches: [
      {
        path: 'src/mock/feature.ts',
        language: 'typescript',
        content: `// AUTO-GENERATED (mock adapter)\nexport function mockFeature(): string {\n  return 'mock';\n}\n`,
        description: 'Mock feature implementation',
      },
    ],
    notes: ['Generated by mock adapter — replace with real model in factory.config.json.'],
    dependencies: [],
  };
}

function mockTesterResponse(taskId: string): object {
  return {
    taskId,
    tests: [
      {
        name: 'mockFeature basic test',
        path: 'src/mock/feature.test.ts',
        content: `import { mockFeature } from './feature';\n\ntest('returns mock string', () => {\n  expect(mockFeature()).toBe('mock');\n});\n`,
        covers: ['mockFeature'],
        framework: 'jest',
      },
    ],
    coverage: ['happy path'],
    setupNotes: [],
  };
}

function mockReviewerResponse(taskId: string): object {
  return {
    taskId,
    verdict: 'approved',
    findings: [],
    summary: 'Mock review: no issues (dry-run).',
  };
}

function mockDomainGuardResponse(taskId: string): object {
  return {
    taskId,
    verdict: 'passed',
    violations: [],
    summary: 'Mock domain guard: no violations (dry-run).',
  };
}

// ---------------------------------------------------------------------------
// Detection helpers
// ---------------------------------------------------------------------------

/**
 * Detect agent role from the FIRST LINE of the system prompt only.
 * Each prompt file starts with "# AGENTNAME" so we only need the header line.
 * Using the full body risks false matches (e.g. "architecture" matching "ARCHITECT").
 */
function detectAgent(systemPrompt: string): string {
  const firstLine = (systemPrompt.split('\n')[0] ?? '').toUpperCase();
  if (firstLine.includes('PLANNER')) return 'planner';
  if (firstLine.includes('ARCHITECT')) return 'architect';
  if (firstLine.includes('CODER')) return 'coder';
  if (firstLine.includes('TESTER')) return 'tester';
  if (firstLine.includes('REVIEWER')) return 'reviewer';
  if (firstLine.includes('DOMAIN')) return 'domain-guard';
  return 'unknown';
}

function extractTaskId(userPrompt: string): string {
  const m = userPrompt.match(/"id"\s*:\s*"([^"]+)"/);
  return m?.[1] ?? 'task-mock-1';
}

// ---------------------------------------------------------------------------
// MockAdapter
// ---------------------------------------------------------------------------

export class MockAdapter implements ModelAdapter {
  readonly name = 'mock:dry-run';

  async call(req: ModelRequest): Promise<ModelResponse> {
    await new Promise((r) => setTimeout(r, 60)); // simulate latency
    const agent = detectAgent(req.systemPrompt);
    const taskId = extractTaskId(req.userPrompt);

    const payload: object =
      agent === 'planner' ? mockPlannerResponse()
      : agent === 'architect' ? mockArchitectResponse(taskId)
      : agent === 'coder' ? mockCoderResponse(taskId)
      : agent === 'tester' ? mockTesterResponse(taskId)
      : agent === 'reviewer' ? mockReviewerResponse(taskId)
      : agent === 'domain-guard' ? mockDomainGuardResponse(taskId)
      : { error: 'Unknown agent type', agent };

    return {
      content: '```json\n' + JSON.stringify(payload, null, 2) + '\n```',
      model: 'mock',
      usage: { promptTokens: 0, completionTokens: 0 },
    };
  }
}
